### ISSUE TITLE
[Feature Request] Provide Global Success/Failure Hooks into Throttling Methods

### ISSUE THREAD

**Issue by mohameddiaa27** [catawiki/rate-limit#8]
## Is your feature request related to a problem? Please describe
I'm always frustrated when I would like to log the rate-limiting behavior for the sake of  monitoring. Adding a global hook into the rate limiting throttle success and failure states allows us to use the `RateLimit.throttle` without worrying about exceptions in many cases. For example

#### Code Block (1)
```ruby
if RateLimit.throttle(topic: 'login', namespace: :user_id, value: user.id)
  login(user)
else
  return false
end
```

If I need to add logging to that I would have to use `RateLimit.throttle!` method instead to be able to catch the `RateLimit::Errors::LimitExceededError` error, as follows

#### Code Block (2)

```ruby
begin
  RateLimit.throttle!(topic: 'login', namespace: :user_id, value: user.id)
  Logger.post(event: 'RateLimitSucceeded', topic: 'login', value: user.id)
  login(user)
rescue RateLimit::Errors::LimitExceededError => e
  Logger.post(event:  'RateLimitFailed', topic: e.topic, value: user.id, threshold: e.threshold, interval: e.interval)
  return false
end
```

## Describe the solution you'd like
I would like to be able to configure a global hooks to the throttler though the configuration. Something like:

```ruby
RateLimit.configure do |config|
  config.on_success = proc { |topic, namespace,  value|
    # Success Logging Logic Goes HERE
    Logger.post(event: 'RateLimitSucceeded', topic: topic, value: value)
  }

  config.on_failure = proc { |topic,  namespace,  value,  threshold,  interval|
    # Failure Logging Logic Goes HERE
    Logger.post(event:  'RateLimitFailed', topic: topic, value: value, threshold: threshold, interval: interval)
  }
end
```

Therefore I would be able to use `Code Block (1)` and ensure that the `on_success` and `on_failure` hooks will take care of the given proc logic (logging in my example) on every usage of the throttling methods

## Describe alternatives you've considered
Replicating the logging logic in every usage of the throttle as shown in `Code Block (2)`

**Additional context**
- NONE

**Comment by dhruvCW** [comment]
Personally I don't like global actions, rarely is the case that you need global actions based on success or failure logic.

in this particular usage I think a result object might be a better choice so the if `RateLimit.throttle` returns a `Result` the code block could look something like

```ruby
result = RateLimit.throttle!(topic: 'login', namespace: :user_id, value: user.id)
if result.limit_exceeded?
  Logger.post(event:  'RateLimitFailed', topic: result.topic, value: user.id, threshold: result.threshold, interval: result.interval)
  return false
else
  Logger.post(event: 'RateLimitSucceeded', topic: 'login', value: user.id)
  login(user)
end
```

wdyt ?

**Comment by mohameddiaa27** [comment]
@dhruvCW I like the idea of result object, it decreases the need of dealing with exceptions manually 👍🏻

However it does bot solve my issue, I would still have to write duplicate logging logic every time I need to throttle (5 times in my case).

I have also considered building my interface in my app but I didn't like that since i need to clone it to other services.

**Comment by dhruvCW** [comment]
>However it does not solve my issue, I would still have to write duplicate logging logic every time I need to throttle (5 times in my case).

oh, I guess your case is the rare situation wherein a global hook makes sense 👍 .
